Repository rehlds/ReGameDLL_CS, pull requests merged in 2021-08, with the labels that each got.

#665 Add new CVar `sv_allchat`
  README.md
  dist/game.cfg
  regamedll/dlls/client.cpp
  regamedll/dlls/game.cpp
  regamedll/dlls/game.h
Labels: Type: Enhancement, Priority: Low, Priority: Medium, Status: Completed

#607 Implement new player hooks
  regamedll/dlls/API/CAPI_Impl.cpp
  regamedll/dlls/API/CAPI_Impl.h
  regamedll/dlls/player.cpp
  regamedll/dlls/player.h
  regamedll/public/regamedll/regamedll_api.h
  regamedll/version/version.h
Labels: Type: Enhancement, Priority: Low, Status: Completed

#662 Fix "use accuracy from last bullet fired earlier" glitch.
  regamedll/dlls/weapons.cpp
  regamedll/dlls/weapons.h
Labels: Type: Bug in original gamedll, Priority: Medium, Status: Completed

#663 Implement `CBasePlayer::Observer_SetMode` hook
  regamedll/dlls/API/CAPI_Impl.cpp
  regamedll/dlls/API/CAPI_Impl.h
  regamedll/dlls/observer.cpp
  regamedll/dlls/player.h
  regamedll/public/regamedll/regamedll_api.h
Labels: Type: Enhancement, Priority: Low, Status: Completed
