Repository rehlds/ReGameDLL_CS, pull requests merged in 2022-12, with the labels that each got.

#788 fix: Reset immunity effects always
  regamedll/dlls/API/CSPlayer.cpp
  regamedll/dlls/player.cpp
  regamedll/public/regamedll/API/CSPlayer.h
Labels: Type: Bug

#798 little code fixes
  regamedll/dlls/vehicle.cpp
  regamedll/dlls/weapons.cpp
Labels: Priority: Low

#748 Fix: `TimeBasedDamage` Paralyze typo
  regamedll/dlls/basemonster.h
  regamedll/dlls/player.cpp
Labels: Priority: Low, Type: Maintenance

#754 Implement `game_round_start` & `game_entity_restart` triggers
  regamedll/dlls/multiplay_gamerules.cpp
  regamedll/dlls/util.cpp
Labels: Type: Enhancement, Priority: Low, Status: Completed

#653 FIX: Unexpected behavior with `mp_forcerespawn`
  regamedll/dlls/API/CSPlayer.cpp
  regamedll/dlls/bot/cs_bot_manager.cpp
  regamedll/dlls/client.cpp
  regamedll/dlls/player.cpp
  regamedll/dlls/player.h
Labels: Type: Bug, Priority: Low, Status: Completed

#796 New entity `trigger_bomb_reset`
  regamedll/CMakeLists.txt
  regamedll/dlls/addons/trigger_bomb_reset.cpp
  regamedll/dlls/addons/trigger_bomb_reset.h
  regamedll/dlls/player.cpp
  regamedll/dlls/weapons.cpp
  regamedll/dlls/weapons.h
  regamedll/dlls/wpn_shared/wpn_c4.cpp
  regamedll/extra/Toolkit/GameDefinitionFile/regamedll-cs.fgd
  regamedll/msvc/ReGameDLL.vcxproj
  regamedll/msvc/ReGameDLL.vcxproj.filters
  regamedll/public/regamedll/API/CSInterfaces.h
  regamedll/regamedll/dlls.h
Labels: Type: Enhancement

#800 CI: Keep the `ICC` build for releases only
  .github/workflows/build.yml
Labels: Type: Enhancement, Priority: Low, Type: Maintenance
