Repository rehlds/ReGameDLL_CS, pull requests merged in 2023-09, with the labels that each got.

#853 Ensure m_pDriver assignation on func_vehicle only
  regamedll/dlls/player.cpp
Labels: Type: Bug

#861 `FIX`: Reloading animation bug while holding weapon with altered Maxclip
  regamedll/dlls/client.cpp
  regamedll/dlls/weapontype.cpp
  regamedll/dlls/weapontype.h
Labels: Type: Bug in original gamedll, Priority: Low, Status: Completed

#858 Add an extended player's DeathMsg message
  README.md
  dist/game.cfg
  regamedll/dlls/API/CAPI_Impl.cpp
  regamedll/dlls/API/CAPI_Impl.h
  regamedll/dlls/API/CSPlayer.cpp
  regamedll/dlls/cbase.cpp
  regamedll/dlls/cbase.h
  regamedll/dlls/client.cpp
  regamedll/dlls/combat.cpp
  regamedll/dlls/game.cpp
  regamedll/dlls/game.h
  regamedll/dlls/gamerules.h
  regamedll/dlls/multiplay_gamerules.cpp
  regamedll/dlls/player.cpp
  regamedll/dlls/player.h
  regamedll/dlls/weapons.cpp
  regamedll/msvc/ReGameDLL.vcxproj
  regamedll/msvc/ReGameDLL.vcxproj.filters
  regamedll/public/regamedll/API/CSEntity.h
  regamedll/public/regamedll/API/CSPlayer.h
  regamedll/public/regamedll/regamedll_api.h
  regamedll/public/utlarray.h
Labels: Type: Enhancement, Priority: Low
