Repository rehlds/ReGameDLL_CS, pull requests merged in 2023-07, with the labels that each got.

#836 `CZero`: Fix broken Career Tasks
  regamedll/dlls/career_tasks.cpp
  regamedll/dlls/player.cpp
Labels: Type: Bug in original gamedll, Priority: Low

#831 Little code cleaning: g_vecAttackDir
  regamedll/dlls/effects.cpp
  regamedll/dlls/player.cpp
  regamedll/dlls/util.cpp
  regamedll/dlls/util.h
  regamedll/dlls/weapons.cpp
Labels: Priority: Low

#827 fix: `bot_profile_db` CVar use
  regamedll/dlls/bot/cs_bot_manager.cpp
Labels: Type: Bug in original gamedll, Priority: Low, Status: Completed

#483 New CVar: `mp_dying_time`
  README.md
  dist/game.cfg
  regamedll/dlls/game.cpp
  regamedll/dlls/game.h
  regamedll/dlls/gamerules.h
  regamedll/dlls/player.cpp
Labels: Type: Help wanted, Type: Enhancement, Priority: Low, Status: On hold

#845 `mp_fadetoblack` fade timings now depends from `mp_dying_time` CVar
  regamedll/dlls/API/CSPlayer.cpp
  regamedll/dlls/animating.cpp
  regamedll/dlls/animation.cpp
  regamedll/dlls/animation.h
  regamedll/dlls/cbase.h
  regamedll/dlls/client.cpp
  regamedll/dlls/combat.cpp
  regamedll/dlls/multiplay_gamerules.cpp
  regamedll/dlls/observer.cpp
  regamedll/dlls/observer.h
  regamedll/dlls/player.cpp
  regamedll/dlls/player.h
Labels: Type: Bug, Type: Enhancement, Priority: Low
