Repository rehlds/ReGameDLL_CS, pull requests merged in 2024-08, with the labels that each got.

#982 Fix: `ammo`/`weapons` respawn behavior
  regamedll/dlls/ammo.cpp
  regamedll/dlls/multiplay_gamerules.cpp
  regamedll/dlls/weapons.cpp
Labels: Type: Bug in original gamedll, Type: Enhancement, Status: Completed

#983 Feature: ConVars for `weapon`/`item`/`ammo` respawn time
  README.md
  dist/game.cfg
  regamedll/dlls/game.cpp
  regamedll/dlls/game.h
  regamedll/dlls/multiplay_gamerules.cpp
Labels: Type: Enhancement

#985 Fix Deagle Anim
  regamedll/dlls/wpn_shared/wpn_deagle.cpp
Labels: Type: Bug
